## set up pvc (Persistent Volume Claims)  for labelstudio node data-labelstudio-postgresql-0
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-labelstudio-postgresql-0
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: gp2  # Add the storage class name here
